#testing1
steps:
- name: 'docker.io/godatadriven/pyspark'
  id: Test
  entrypoint: /bin/sh
  args:
  - -c
  - 'pip install pytest && pip install -r requirements.txt && python test/test.py'
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  id: Deploy
  entrypoint: bash
  args: [ '-c', 'if [ "$BRANCH_NAME" == "master" ]; 
  then echo "$BRANCH_NAME" && gsutil -m rsync -d -r ./dags gs://${_COMPOSER_BUCKET}/dags
  && gsutil -m rsync -d -r ./data gs://${_COMPOSER_BUCKET}/data
  && gsutil -m rsync -d -r ./sparkfiles gs://${_COMPOSER_BUCKET}/sparkfiles; 
  else echo "Working on $BRANCH_NAME"; fi']
substitutions:
    _COMPOSER_BUCKET: us-east1-dev-cloud-composer-fb241977-bucket